name: 'Download Kernel Repository'
description: 'Initialize and sync Android kernel source repository'

inputs:
  repo:
    description: 'Kernel repository'
    required: true

runs:
  using: composite
  steps:
    - name: Initialize and Sync Kernel Repository
      id: sync
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        # Initialize repo with the target branch
        repo init -u https://android.googlesource.com/kernel/manifest -b ${{inputs.repo }} --depth=1
        
        # Sync kernel source
        repo --trace sync -c -j$(nproc --all) --fail-fast --no-tags --force-sync --no-clone-bundle
